### PR TITLE
Feature/tx result handler

### LINKED ISSUE #1: Cosmos 0.38 support
Currently "Sacco" intercepts LCD responses that are based on the old Cosmos SDK; it needs to correctly intercept responses from the new SDK version 0.38 while maintaining compatibility with version 0.37. 

In the new version some response 'json' change and it is necessary to manage cases. In case of error, for example, the 'raw_log' can be a string or an object (map); note that only in error responses the code is present. I attach some sample answers.

[Archivio.zip](https://github.com/commercionetwork/sacco.kt/files/4416021/Archivio.zip)

The addresses to test are:
- 'https://lcd-testnet.commercio.network' (old)
- 'https://lcd-internal.commercio.network' (new)

The version developed in 'Dart' of 'Sacco' has already been updated, it can be useful to understand which classes have to be updated.

@marcotradenet

### LINKED ISSUE #2: Derivation path
Currently 'DERIVATION_PATH' is a constant defined in the class 'Wallet', but it must be possible to set it. At the moment the default "derivation path" is this: "m/44'/118'/0'/0/0".

The possibility to modify the last segment of the derivation path, i.e. replace the last number with a positive integer, must be implemented. It must also be verified that the value passed to change the derivation path is really a positive whole number, otherwise it must be rejected.

The version developed in 'Dart' of 'Sacco' has already been updated, it can be useful to understand how the change was implemented.

@marcotradenet

### PR DESCRIPTION
**Pull request by Valentina-92**
Closed commercionetwork/sacco.kt#1
Closed commercionetwork/sacco.kt#2

### CODE REVIEW

**Comment by Valentina-92** [comment]
Per conoscenza: @zenit70

**Review by marcotradenet — COMMENTED** [review]
In the new version of the chain the account object changes: "account_number" and "sequence" are integers. Have you made any changes for this?    
    
I believe that tests should be implemented to verify the processing of transaction responses.
```
/src/test/kotlin/network/commercio/sacco/utils/LCDServiceTests.kt
```

**Comment by zenit70** [comment]
While I'm very rusty with Kotlin, I've seen that no changes have been made to the method for fetching account data.

In the Dart version I had to add the possibility to manage different types of data for the account, because the new version of the SDK returns different types of data.

@Valentina-92 @marcotradenet

**Comment by zenit70** [comment]
It seems to me that the necessary changes have been made, I cannot comment on their effectiveness because I have not used Kotlin lately.

@Valentina-92

**Comment by Valentina-92** [comment]
@marcotradenet thanks for watching.

I fixed it: now "account_number" and "sequence" can accept both strings and integers.

@zenit70

**Comment by zenit70** [comment]
@marcotradenet I think Travis is stuck again.

**Review by zenit70 — APPROVED** [review]

**Review by marcotradenet — APPROVED** [review]

**Pull request merged**
